# Generated by Django 2.1.4 on 2019-01-20 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttodo',
            name='priority',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='ttodo',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
